### PR TITLE
Add support to JSON literals, configure property nesting, original sections inclusion and array literal parsing behaviour

### PR DESCRIPTION
**Pull request by javiermarinros**
I've added support for enable/disable property nesting, set the behaviour of the array literals (parse json / parse simple arrays / no parse at all) and another useful option to clean up the final array by removing the original pre-inherited sections. Also, the final output order now respect the original sections order. And some bugs are fixed (they're explained in the commits).

This description for JSON literals can be incluided in the README:

Dictionaries and complex structures

Besides arrays, you can create dictionaries and more complex structures using JSON syntax. For example, you can use:

```
 staff = '{
    "boss": {
       "name": "John", 
       "age": 42 
    }, 
    "staff": [
       {
          "name": "Mark" 
          "age": 35 
       }, 
       {
          "name": "Bill" 
          "age": 44 
       } 
    ] 
 } '
```

NOTE: Remember to wrap the JSON strings in single quotes for a correct analysis. The JSON names must be enclosed in double quotes and trailing commas are not allowed.

### CODE REVIEW

**Comment by austinhyde** [comment]
I like a lot of your fixes, but I'm a little stumped as to when you would embed JSON in this INI format, when it supports most everything JSON does any way. What use case do you have for that?

If you would update the README with your proposed changes, and add a few unit tests that cover this behavior, I'd like to merge these changes in!

Finally: I see you closed three other Pull Requests before this one - GitHub actually allows you to continue adding commits to a PR after you open it. All you have to do is push to the branch you opened the PR for (master, in your case).

Thanks!

**Comment by javiermarinros** [comment]
Thank you very much for your comments!

I added the JSON support because I needed some easy way to create dictionaries and complex structures in my INI files. For example, this functionality can be useful to initialize class instances.

The ideal solution would be to use a syntax similar to the arrays, something like [a:1, b:2, c:3], but implement this is complicated and it's like reinvent the wheel, because JSON format do more than that and as easy as using `json_decode`. Besides, it's easy to enable/disable this functionality through class properties. I've enabled it, but I think that you're the most suitable to decide if the JSON parsing is activated or not by default.

I've added the things you asked to the Pull Request. I hope they're what you expected.

Thanks

**Comment by pyrsmk** [comment]
Why don't you use simple JSON files for your JSON data rather than encapsulates in an INI file?

**Comment by javiermarinros** [comment]
Because most of my data are scalar values which I prefer to describe using INI as a simpler and cleaner syntax. Here I have an snippet of my app config where I use JSON:

```
i18n.enabled = true
i18n.default = en
i18n.current = es
i18n.time_zone = Europe/Madrid

templates.engines = '{"php":"PHP", "twig":"Twig"}'
templates.optimize = true
templates.cache = true

assets.versions.jquery = 2.1.0
```

As you can see, I'm well using INI for most of it, but in the particular case of `templates.engines` I need a dictionary to associate each file extension with each engine, that's why I implemented the JSON support.

**Comment by austinhyde** [comment]
But why not this?

```
templates.engines.php = PHP
templates.engines.twig = Twig
```

**Comment by javiermarinros** [comment]
Because I already use dots for each different <em>namespace</em> (i18n, templates, assets, etc.) That's why also created the `property_nesting` toggle.

Later, in the app, I just use:

   Config::get('i18n.enabled')

**Comment by javiermarinros** [comment]
Thank you!

**Pull request merged**
